export const DEFAULT_WORD_PACK = {
  id: "default",
  name: "Zones of Regulation (Default)",
  description: "The original 300-word bank covering the full emotional spectrum for all ages.",
  zones: {
    blue: {
      label: "Low Energy",
      words: [
        "Sad", "Tired", "Bored", "Sick", "Exhausted",
        "Down", "Lonely", "Drained", "Sleepy", "Withdrawn",
        "Hopeless", "Empty", "Gloomy", "Sluggish", "Disconnected",
        "Unmotivated", "Flat", "Melancholy", "Numb", "Weary",
        "Defeated", "Low", "Lethargic", "Depressed", "Discouraged",
        "Heavy", "Apathetic", "Listless", "Fatigued", "Miserable",
        "Homesick", "Hurt", "Grief", "Sorrow", "Disheartened",
        "Mopey", "Blah", "Sulky", "Tearful", "Blue",
        "Unwell", "Drowsy", "Slow", "Passive", "Weak",
        "Fragile", "Vulnerable", "Depleted", "Spent", "Burned Out",
        "Unfocused", "Foggy", "Hazy", "Distant", "Checked Out",
        "Shut Down", "Frozen", "Lost", "Aimless", "Indifferent",
        "Uninspired", "Dull", "Monotone", "Somber", "Wistful",
        "Resigned", "Helpless", "Powerless", "Disengaged", "Hollow",
        "Quiet", "Still", "Subdued", "Muted", "Dim",
      ],
    },
    green: {
      label: "Calm & Ready",
      words: [
        "Happy", "Calm", "Focused", "Content", "Ready",
        "Grateful", "Relaxed", "Peaceful", "Balanced", "Cheerful",
        "Comfortable", "Confident", "Optimistic", "Pleased", "Satisfied",
        "Steady", "Centered", "Patient", "Kind", "Friendly",
        "Thoughtful", "Mindful", "Present", "Grounded", "Secure",
        "Safe", "Motivated", "Engaged", "Interested", "Curious",
        "Hopeful", "Joyful", "Loving", "Caring", "Compassionate",
        "Generous", "Playful", "Amused", "Delighted", "Warm",
        "Cozy", "Gentle", "Tender", "Serene", "Tranquil",
        "Mellow", "Easygoing", "Cooperative", "Helpful", "Accepting",
        "Brave", "Proud", "Accomplished", "Capable", "Strong",
        "Determined", "Energized", "Refreshed", "Alive", "Vibrant",
        "Connected", "Appreciated", "Valued", "Respected", "Understood",
        "Supported", "Included", "Welcome", "Belonging", "Thankful",
        "Attentive", "Creative", "Inspired", "Flexible", "Open",
      ],
    },
    yellow: {
      label: "Heightened",
      words: [
        "Frustrated", "Anxious", "Excited", "Nervous", "Silly",
        "Worried", "Fidgety", "Restless", "Hyper", "Overwhelmed",
        "Embarrassed", "Confused", "Surprised", "Shocked", "Startled",
        "Impatient", "Irritated", "Annoyed", "Tense", "Stressed",
        "Uneasy", "Apprehensive", "Jittery", "Edgy", "Antsy",
        "Distracted", "Scattered", "Flustered", "Unsettled", "Agitated",
        "Pressured", "Rushed", "Hurried", "Frantic", "Hectic",
        "Wiggly", "Giggly", "Goofy", "Wild", "Wired",
        "Jealous", "Envious", "Suspicious", "Doubtful", "Uncertain",
        "Insecure", "Self-Conscious", "Awkward", "Uncomfortable", "Cranky",
        "Grumpy", "Moody", "Sensitive", "Reactive", "On Edge",
        "Wound Up", "Keyed Up", "Amped", "Buzzed", "Revved Up",
        "Overstimulated", "Sensory Overload", "Wary", "Guarded", "Defensive",
        "Stubborn", "Resistant", "Defiant", "Argumentative", "Confrontational",
        "Whiny", "Dramatic", "Intense", "Excitable", "Impulsive",
      ],
    },
    red: {
      label: "Extreme",
      words: [
        "Angry", "Furious", "Terrified", "Enraged", "Explosive",
        "Panicked", "Out of Control", "Devastated", "Aggressive", "Hostile",
        "Violent", "Raging", "Seething", "Livid", "Irate",
        "Incensed", "Infuriated", "Wrathful", "Vengeful", "Hateful",
        "Hysterical", "Screaming", "Crying Uncontrollably", "Sobbing", "Wailing",
        "Petrified", "Paralyzed", "Horrified", "Terrorized", "Traumatized",
        "Meltdown", "Tantrum", "Rampage", "Chaos", "Frenzy",
        "Shattered", "Crushed", "Destroyed", "Broken", "Wrecked",
        "Elated", "Euphoric", "Manic", "Ecstatic", "Delirious",
        "Combative", "Threatening", "Intimidating", "Menacing", "Bullying",
        "Unhinged", "Snapped", "Lost It", "Blinded by Rage", "Seeing Red",
        "Desperate", "Frenzied", "Crazed", "Berserk", "Savage",
        "Overwhelmed Completely", "Shutdown", "Dissociated", "Spiraling", "Imploding",
        "Exploding", "Erupting", "Boiling Over", "White Hot", "Volcanic",
        "Inconsolable", "Uncontrollable", "Consumed", "Possessed", "Ablaze",
      ],
    },
  },
};
